spring:
  application:
    name: store-detective-service
  sql:
    init:
      platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:data/stores.sql';
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
caching:
  spring:
    storesTTL: 21600000 # 6 hours

logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}) [%thread] %clr(%-5level) %logger{36} %clr(%replace([CorrId:%X{Correlation-Id}]){'\\[CorrId:\\]','-'}) - %msg%n"

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN